source "https://rubygems.org"

# Jekyll and plugins
gem "jekyll", "~> 4.4.1"
gem "minima", "~> 2.5"

group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
  gem "jekyll-sass-converter", "~> 3.0"
  gem "jekyll-seo-tag"
end

# Platform-specific gems
platforms :windows do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1", :platforms => [:windows]
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
